### ISSUE TITLE
runtime problem

### ISSUE THREAD

**Issue by mzy97** [DylanWusee/pointconv#9]
HI, thank you for the work
when i running the training code, i encounter error
`Traceback (most recent call last):
  File "train_scannet_IoU.py", line 55, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/home/muzhengyang/anaconda3/envs/pointconv/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/unsullied/sharefs/muzhengyang/dataroot1/pointconv/pointconv/models/pointconv_weight_density_n16.py", line 10, in <module>
    from PointConv import feature_encoding_layer, feature_decoding_layer
  File "/unsullied/sharefs/muzhengyang/dataroot1/pointconv/pointconv/PointConv.py", line 20, in <module>
    from tf_interpolate import three_nn, three_interpolate
  File "/unsullied/sharefs/muzhengyang/dataroot1/pointconv/pointconv/tf_ops/3d_interpolation/tf_interpolate.py", line 8, in <module>
    interpolate_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_interpolate_so.so'))
  File "/home/muzhengyang/anaconda3/envs/pointconv/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /unsullied/sharefs/muzhengyang/dataroot1/pointconv/pointconv/tf_ops/3d_interpolation/tf_interpolate_so.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`

I have compiled the pointnet custom operation.

how to fix it?

thanks

**Comment by iris0329** [comment]
you should re-compile the pointnet operation.

**Comment by mzy97** [comment]
> you should re-compile the pointnet operation.

in my situation, this problem was due to the not-enough GPU memory allocation. thank you for reply
